/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as Day2RouteImport } from './routes/day2'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedNontech1RouteImport } from './routes/_authenticated/nontech1'
import { Route as AuthenticatedNontech2RouteImport } from './routes/_authenticated/nontech2'
import { Route as AuthenticatedTech1RouteImport } from './routes/_authenticated/tech1'
import { Route as AuthenticatedTech2RouteImport } from './routes/_authenticated/tech2'
import { Route as Day2IndexRouteImport } from './routes/day2/index'
import { Route as Day2Nontech3RouteImport } from './routes/day2/nontech3'
import { Route as Day2Tech3RouteImport } from './routes/day2/tech3'
import { Route as AuthenticatedEventsTrackSlotRouteImport } from './routes/_authenticated/events.$track.$slot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Day2Route = Day2RouteImport.update({
  id: '/day2',
  path: '/day2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNontech1Route = AuthenticatedNontech1RouteImport.update({
  id: '/nontech1',
  path: '/nontech1',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNontech2Route = AuthenticatedNontech2RouteImport.update({
  id: '/nontech2',
  path: '/nontech2',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTech1Route = AuthenticatedTech1RouteImport.update({
  id: '/tech1',
  path: '/tech1',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTech2Route = AuthenticatedTech2RouteImport.update({
  id: '/tech2',
  path: '/tech2',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Day2IndexRoute = Day2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Day2Route,
} as any)
const Day2Nontech3Route = Day2Nontech3RouteImport.update({
  id: '/nontech3',
  path: '/nontech3',
  getParentRoute: () => Day2Route,
} as any)
const Day2Tech3Route = Day2Tech3RouteImport.update({
  id: '/tech3',
  path: '/tech3',
  getParentRoute: () => Day2Route,
} as any)
const AuthenticatedEventsTrackSlotRoute =
  AuthenticatedEventsTrackSlotRouteImport.update({
    id: '/$track/$slot',
    path: '/$track/$slot',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/day2': typeof Day2RouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/nontech1': typeof AuthenticatedNontech1Route
  '/nontech2': typeof AuthenticatedNontech2Route
  '/tech1': typeof AuthenticatedTech1Route
  '/tech2': typeof AuthenticatedTech2Route
  '/day2/nontech3': typeof Day2Nontech3Route
  '/day2/tech3': typeof Day2Tech3Route
  '/day2/': typeof Day2IndexRoute
  '/events/$track/$slot': typeof AuthenticatedEventsTrackSlotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/nontech1': typeof AuthenticatedNontech1Route
  '/nontech2': typeof AuthenticatedNontech2Route
  '/tech1': typeof AuthenticatedTech1Route
  '/tech2': typeof AuthenticatedTech2Route
  '/day2/nontech3': typeof Day2Nontech3Route
  '/day2/tech3': typeof Day2Tech3Route
  '/day2': typeof Day2IndexRoute
  '/events/$track/$slot': typeof AuthenticatedEventsTrackSlotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/day2': typeof Day2RouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/nontech1': typeof AuthenticatedNontech1Route
  '/_authenticated/nontech2': typeof AuthenticatedNontech2Route
  '/_authenticated/tech1': typeof AuthenticatedTech1Route
  '/_authenticated/tech2': typeof AuthenticatedTech2Route
  '/day2/nontech3': typeof Day2Nontech3Route
  '/day2/tech3': typeof Day2Tech3Route
  '/day2/': typeof Day2IndexRoute
  '/_authenticated/events/$track/$slot': typeof AuthenticatedEventsTrackSlotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/day2'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/leaderboard'
    | '/nontech1'
    | '/nontech2'
    | '/tech1'
    | '/tech2'
    | '/day2/nontech3'
    | '/day2/tech3'
    | '/day2/'
    | '/events/$track/$slot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/events'
    | '/leaderboard'
    | '/nontech1'
    | '/nontech2'
    | '/tech1'
    | '/tech2'
    | '/day2/nontech3'
    | '/day2/tech3'
    | '/day2'
    | '/events/$track/$slot'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/day2'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/leaderboard'
    | '/_authenticated/nontech1'
    | '/_authenticated/nontech2'
    | '/_authenticated/tech1'
    | '/_authenticated/tech2'
    | '/day2/nontech3'
    | '/day2/tech3'
    | '/day2/'
    | '/_authenticated/events/$track/$slot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  Day2Route: typeof Day2RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day2': {
      id: '/day2'
      path: '/day2'
      fullPath: '/day2'
      preLoaderRoute: typeof Day2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nontech1': {
      id: '/_authenticated/nontech1'
      path: '/nontech1'
      fullPath: '/nontech1'
      preLoaderRoute: typeof AuthenticatedNontech1RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nontech2': {
      id: '/_authenticated/nontech2'
      path: '/nontech2'
      fullPath: '/nontech2'
      preLoaderRoute: typeof AuthenticatedNontech2RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tech1': {
      id: '/_authenticated/tech1'
      path: '/tech1'
      fullPath: '/tech1'
      preLoaderRoute: typeof AuthenticatedTech1RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tech2': {
      id: '/_authenticated/tech2'
      path: '/tech2'
      fullPath: '/tech2'
      preLoaderRoute: typeof AuthenticatedTech2RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/day2/': {
      id: '/day2/'
      path: '/'
      fullPath: '/day2/'
      preLoaderRoute: typeof Day2IndexRouteImport
      parentRoute: typeof Day2Route
    }
    '/day2/nontech3': {
      id: '/day2/nontech3'
      path: '/nontech3'
      fullPath: '/day2/nontech3'
      preLoaderRoute: typeof Day2Nontech3RouteImport
      parentRoute: typeof Day2Route
    }
    '/day2/tech3': {
      id: '/day2/tech3'
      path: '/tech3'
      fullPath: '/day2/tech3'
      preLoaderRoute: typeof Day2Tech3RouteImport
      parentRoute: typeof Day2Route
    }
    '/_authenticated/events/$track/$slot': {
      id: '/_authenticated/events/$track/$slot'
      path: '/$track/$slot'
      fullPath: '/events/$track/$slot'
      preLoaderRoute: typeof AuthenticatedEventsTrackSlotRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
  }
}

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsTrackSlotRoute: typeof AuthenticatedEventsTrackSlotRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsTrackSlotRoute: AuthenticatedEventsTrackSlotRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNontech1Route: typeof AuthenticatedNontech1Route
  AuthenticatedNontech2Route: typeof AuthenticatedNontech2Route
  AuthenticatedTech1Route: typeof AuthenticatedTech1Route
  AuthenticatedTech2Route: typeof AuthenticatedTech2Route
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNontech1Route: AuthenticatedNontech1Route,
  AuthenticatedNontech2Route: AuthenticatedNontech2Route,
  AuthenticatedTech1Route: AuthenticatedTech1Route,
  AuthenticatedTech2Route: AuthenticatedTech2Route,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface Day2RouteChildren {
  Day2Nontech3Route: typeof Day2Nontech3Route
  Day2Tech3Route: typeof Day2Tech3Route
  Day2IndexRoute: typeof Day2IndexRoute
}

const Day2RouteChildren: Day2RouteChildren = {
  Day2Nontech3Route: Day2Nontech3Route,
  Day2Tech3Route: Day2Tech3Route,
  Day2IndexRoute: Day2IndexRoute,
}

const Day2RouteWithChildren = Day2Route._addFileChildren(Day2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  Day2Route: Day2RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
